services:
  # gigachat:
  #   build: ./gigachat-service
  #   command: uvicorn app.main:app --reload --host 0.0.0.0 --port 81
  #   container_name: gigachat
  #   environment:
  #     - CHROMA=chromadb
  #   ports:
  #     - "8001:81"
  #   restart: unless-stopped
  #   networks:
  #     - internal 
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /usr/share/ollama/.ollama:/root/.ollama
    networks:
      - internal
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  llm_rpc:
    build: ./llm_rpc_server
    command: python3 rpc_server.py
    container_name: llm_rpc
    environment:
      - CHROMA=chromadb
      - OLLAMA_HOST=ollama
      - MODEL=deepseek-r1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - ollama
      - chromadb